name: digital_gunluk
description: "A new Flutter project."
publish_to: 'none' # pub.dev'de yayınlamayı engeller

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Yerelleştirme için
    sdk: flutter

  # UI & Temel Yardımcılar
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Dosya Sistemi, İzinler ve Dosya Açma
  path_provider: ^2.1.3
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Zaman ve Bildirimler
  timezone: ^0.10.0
  flutter_local_notifications: ^19.1.0 # Bu sürüm artık timezone ^0.10.0 gerektiriyor

  # API İletişimi için paketler
  dio: ^5.4.1
  json_annotation: ^4.8.1 # Eğer json_serializable kullanıyorsanız bu da olmalı
  shared_preferences: ^2.2.3
  logger: ^2.5.0 # SADECE BU SATIR KALDI (GÜNCEL VERSİYON)

  # Özellikler
  table_calendar: ^3.1.3
  record: ^5.2.1
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true